/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicTransactionsRouteImport } from './routes/api/public/transactions'
import { Route as ApiPublicRegistrationRouteImport } from './routes/api/public/registration'
import { Route as ApiPublicBotSendRouteImport } from './routes/api/public/bot/send'
import { Route as ApiPublicBotLookupRouteImport } from './routes/api/public/bot/lookup'

const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTransactionsRoute = ApiPublicTransactionsRouteImport.update({
  id: '/api/public/transactions',
  path: '/api/public/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegistrationRoute = ApiPublicRegistrationRouteImport.update({
  id: '/api/public/registration',
  path: '/api/public/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotSendRoute = ApiPublicBotSendRouteImport.update({
  id: '/api/public/bot/send',
  path: '/api/public/bot/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBotLookupRoute = ApiPublicBotLookupRouteImport.update({
  id: '/api/public/bot/lookup',
  path: '/api/public/bot/lookup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/registration': typeof ApiPublicRegistrationRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/api/public/bot/lookup': typeof ApiPublicBotLookupRoute
  '/api/public/bot/send': typeof ApiPublicBotSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/registration': typeof ApiPublicRegistrationRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/api/public/bot/lookup': typeof ApiPublicBotLookupRoute
  '/api/public/bot/send': typeof ApiPublicBotSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/registration': typeof ApiPublicRegistrationRoute
  '/api/public/transactions': typeof ApiPublicTransactionsRoute
  '/api/public/bot/lookup': typeof ApiPublicBotLookupRoute
  '/api/public/bot/send': typeof ApiPublicBotSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/faq'
    | '/how-it-works'
    | '/dashboard'
    | '/api/public/registration'
    | '/api/public/transactions'
    | '/api/public/bot/lookup'
    | '/api/public/bot/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/faq'
    | '/how-it-works'
    | '/dashboard'
    | '/api/public/registration'
    | '/api/public/transactions'
    | '/api/public/bot/lookup'
    | '/api/public/bot/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/faq'
    | '/how-it-works'
    | '/_authenticated/dashboard'
    | '/api/public/registration'
    | '/api/public/transactions'
    | '/api/public/bot/lookup'
    | '/api/public/bot/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ApiPublicRegistrationRoute: typeof ApiPublicRegistrationRoute
  ApiPublicTransactionsRoute: typeof ApiPublicTransactionsRoute
  ApiPublicBotLookupRoute: typeof ApiPublicBotLookupRoute
  ApiPublicBotSendRoute: typeof ApiPublicBotSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/transactions': {
      id: '/api/public/transactions'
      path: '/api/public/transactions'
      fullPath: '/api/public/transactions'
      preLoaderRoute: typeof ApiPublicTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/registration': {
      id: '/api/public/registration'
      path: '/api/public/registration'
      fullPath: '/api/public/registration'
      preLoaderRoute: typeof ApiPublicRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/send': {
      id: '/api/public/bot/send'
      path: '/api/public/bot/send'
      fullPath: '/api/public/bot/send'
      preLoaderRoute: typeof ApiPublicBotSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bot/lookup': {
      id: '/api/public/bot/lookup'
      path: '/api/public/bot/lookup'
      fullPath: '/api/public/bot/lookup'
      preLoaderRoute: typeof ApiPublicBotLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  ApiPublicRegistrationRoute: ApiPublicRegistrationRoute,
  ApiPublicTransactionsRoute: ApiPublicTransactionsRoute,
  ApiPublicBotLookupRoute: ApiPublicBotLookupRoute,
  ApiPublicBotSendRoute: ApiPublicBotSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
